//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POW_REST_2015.Models2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaEventMetric
    {
        public int ID { get; set; }
        public int EventID { get; set; }
        public int MetricTypeID { get; set; }
        public string Value { get; set; }
        public Nullable<bool> IsUsed { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    
        public virtual MediaEvent MediaEvent { get; set; }
        public virtual MediaEvent MediaEvent1 { get; set; }
    }
}
