//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POW_REST_2015.Models2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaEventSubType
    {
        public MediaEventSubType()
        {
            this.MediaEventMetricTypes = new HashSet<MediaEventMetricType>();
        }
    
        public int ID { get; set; }
        public Nullable<int> MediaTypeID { get; set; }
        public Nullable<int> UID { get; set; }
        public string Name { get; set; }
        public string Year { get; set; }
        public Nullable<bool> IsUsed { get; set; }
    
        public virtual ICollection<MediaEventMetricType> MediaEventMetricTypes { get; set; }
        public virtual MediaEventType MediaEventType { get; set; }
        public virtual MediaEventType MediaEventType1 { get; set; }
    }
}
