//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POW_REST_2015.Models2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaEvent
    {
        public MediaEvent()
        {
            this.MediaEventMetrics = new HashSet<MediaEventMetric>();
            this.MediaEventMetrics1 = new HashSet<MediaEventMetric>();
        }
    
        public int ID { get; set; }
        public Nullable<int> MediaID { get; set; }
        public string CreatorID { get; set; }
        public string MediaType { get; set; }
        public string EventTitle { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public string Option1 { get; set; }
        public string Option2 { get; set; }
        public string Option3 { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string IsUsed { get; set; }
        public string Year { get; set; }
        public string Count2 { get; set; }
        public string Description2 { get; set; }
        public Nullable<int> EventTypeID { get; set; }
        public Nullable<int> EventSubTypeID { get; set; }
    
        public virtual ICollection<MediaEventMetric> MediaEventMetrics { get; set; }
        public virtual ICollection<MediaEventMetric> MediaEventMetrics1 { get; set; }
    }
}
