//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POW_REST_2015.Models2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaEventType
    {
        public MediaEventType()
        {
            this.MediaEventSubTypes = new HashSet<MediaEventSubType>();
            this.MediaEventSubTypes1 = new HashSet<MediaEventSubType>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string IsUsed { get; set; }
        public string Year { get; set; }
        public string UID { get; set; }
    
        public virtual ICollection<MediaEventSubType> MediaEventSubTypes { get; set; }
        public virtual ICollection<MediaEventSubType> MediaEventSubTypes1 { get; set; }
    }
}
