//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POW_REST_2015.Models2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PowEntities4 : DbContext
    {
        public PowEntities4()
            : base("name=PowEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Medium> Media { get; set; }
        public virtual DbSet<MediaEvent> MediaEvents { get; set; }
        public virtual DbSet<MediaEventDate> MediaEventDates { get; set; }
        public virtual DbSet<MediaEventMetric> MediaEventMetrics { get; set; }
        public virtual DbSet<MediaEventMetricType> MediaEventMetricTypes { get; set; }
        public virtual DbSet<MediaEventSubType> MediaEventSubTypes { get; set; }
        public virtual DbSet<MediaEventType> MediaEventTypes { get; set; }
        public virtual DbSet<MediaMember> MediaMembers { get; set; }
    }
}
