//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Extension_2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalTeam
    {
        public int ID { get; set; }
        public int ProjectID { get; set; }
        public string TeamUID { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string IsUsed { get; set; }
    }
}
