//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Extension_2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medium
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string CreatorID { get; set; }
        public string Program { get; set; }
        public string Year { get; set; }
        public string Month { get; set; }
        public string County { get; set; }
        public string Impact { get; set; }
        public string Feedback { get; set; }
        public string IsUsed { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    }
}
