//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Extension_2017.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PowEntities : DbContext
    {
        public PowEntities()
            : base("name=PowEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContactApp> ContactApps { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<StaffDirectory> StaffDirectories { get; set; }
        public virtual DbSet<PowUser> PowUsers { get; set; }
        public virtual DbSet<Participant> Participants { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<AdditionalTeam> AdditionalTeams { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<ActivityProject> ActivityProjects { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<common> commons { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Medium> Media { get; set; }
        public virtual DbSet<MediaEvent> MediaEvents { get; set; }
        public virtual DbSet<MediaType> MediaTypes { get; set; }
        public virtual DbSet<MediaEventType> MediaEventTypes { get; set; }
        public virtual DbSet<Year> Years { get; set; }
        public virtual DbSet<Activity> Activities { get; set; }
    }
}
