//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Extension_2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int ID { get; set; }
        public string UID { get; set; }
        public string Title { get; set; }
        public string IsPlan { get; set; }
        public string IsUnplan { get; set; }
        public string IsUsed { get; set; }
        public string Type { get; set; }
        public Nullable<int> Order { get; set; }
        public string Year { get; set; }
        public string ApproverID { get; set; }
    }
}
