//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POW_REST_2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> ActivityID { get; set; }
        public Nullable<int> Attendees { get; set; }
        public string ContactType { get; set; }
        public string Program { get; set; }
        public string Year { get; set; }
        public string Description { get; set; }
        public string raian { get; set; }
        public string rapi { get; set; }
        public string rblack { get; set; }
        public string rfmale { get; set; }
        public string rhisp { get; set; }
        public string rmale { get; set; }
        public string rnftf { get; set; }
        public string rother { get; set; }
        public string rwhite { get; set; }
        public string ryouth { get; set; }
        public string uadult { get; set; }
        public string uaian { get; set; }
        public string uapi { get; set; }
        public string ublack { get; set; }
        public string ufmale { get; set; }
        public string uhisp { get; set; }
        public string umale { get; set; }
        public string unftf { get; set; }
        public string uother { get; set; }
        public string uwhite { get; set; }
        public string uyouth { get; set; }
        public string CreatorID { get; set; }
        public string IsUsed { get; set; }
        public string radult { get; set; }
        public string Evaluation { get; set; }
        public string ExternalFactor { get; set; }
        public string Outcomes { get; set; }
        public string FileLink { get; set; }
        public string County { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string rMore { get; set; }
        public string uMore { get; set; }
        public string IsPlan { get; set; }
        public string mraian { get; set; }
        public string mrapi { get; set; }
        public string mrblack { get; set; }
        public string mrfmale { get; set; }
        public string mrhisp { get; set; }
        public string mrmale { get; set; }
        public string mrother { get; set; }
        public string mrwhite { get; set; }
        public string mryouth { get; set; }
        public string muadult { get; set; }
        public string muaian { get; set; }
        public string muapi { get; set; }
        public string mublack { get; set; }
        public string mufmale { get; set; }
        public string muhisp { get; set; }
        public string mumale { get; set; }
        public string muother { get; set; }
        public string muwhite { get; set; }
        public string muyouth { get; set; }
        public string mradult { get; set; }
        public string mrMore { get; set; }
        public string muMore { get; set; }
        public Nullable<bool> IsMultistate { get; set; }
        public string uNonHispanic { get; set; }
        public string rNonHispanic { get; set; }
        public string muNonHispanic { get; set; }
        public string mrNonHispanic { get; set; }
        public string unknown { get; set; }
        public string munknown { get; set; }
        public string unknownGender { get; set; }
        public string unknownAge { get; set; }
        public string unknownRace { get; set; }
        public string unknownEth { get; set; }
        public string munknownGender { get; set; }
        public string munknownAge { get; set; }
        public string munknownRace { get; set; }
        public string munknownEth { get; set; }
    }
}
