//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POW_REST_2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadPerson
    {
        public int Id { get; set; }
        public string Teamcode { get; set; }
        public string Username { get; set; }
        public string Responsibility { get; set; }
        public string JobTitle { get; set; }
        public string Year { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    }
}
