//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POW_REST_2015.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PowEntities2 : DbContext
    {
        public PowEntities2()
            : base("name=PowEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdditionalTeam> AdditionalTeams { get; set; }
        public virtual DbSet<county> counties { get; set; }
        public virtual DbSet<PowUser> PowUsers { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectsHistory> ProjectsHistories { get; set; }
        public virtual DbSet<StaffDirectory> StaffDirectories { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<ActivityProject> ActivityProjects { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<TransactionLog> TransactionLogs { get; set; }
        public virtual DbSet<LeadPerson> LeadPersons { get; set; }
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<vCountySet> vCountySets { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<ProjectInstructor> ProjectInstructors { get; set; }
        public virtual DbSet<ProjectLeadPerson> ProjectLeadPersons { get; set; }
    
        [DbFunction("PowEntities2", "SplitStrings")]
        public virtual IQueryable<SplitStrings_Result> SplitStrings(string list, string delimiter)
        {
            var listParameter = list != null ?
                new ObjectParameter("List", list) :
                new ObjectParameter("List", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("Delimiter", delimiter) :
                new ObjectParameter("Delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<SplitStrings_Result>("[PowEntities2].[SplitStrings](@List, @Delimiter)", listParameter, delimiterParameter);
        }
    
        public virtual ObjectResult<getCountySets_Result> getCountySets(string year)
        {
            var yearParameter = year != null ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCountySets_Result>("getCountySets", yearParameter);
        }
    
        public virtual ObjectResult<GetContactSummarybyCounty_Result> GetContactSummarybyCounty(string county, string year)
        {
            var countyParameter = county != null ?
                new ObjectParameter("county", county) :
                new ObjectParameter("county", typeof(string));
    
            var yearParameter = year != null ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetContactSummarybyCounty_Result>("GetContactSummarybyCounty", countyParameter, yearParameter);
        }
    }
}
