//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POW_REST_2015.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PowSumEntities : DbContext
    {
        public PowSumEntities()
            : base("name=PowSumEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblRow> tblRows { get; set; }
        public virtual DbSet<tblSection> tblSections { get; set; }
        public virtual DbSet<tblSummary> tblSummaries { get; set; }
        public virtual DbSet<tblCivilRight> tblCivilRights { get; set; }
        public virtual DbSet<tblOtherAdviser> tblOtherAdvisers { get; set; }
        public virtual DbSet<tblDeskAudit> tblDeskAudits { get; set; }
        public virtual DbSet<tblDeskAuditsNEW> tblDeskAuditsNEWs { get; set; }
    }
}
