//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POW_REST_2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int ID { get; set; }
        public string Year { get; set; }
        public string UID { get; set; }
        public string PlanType { get; set; }
        public string ProjectTitle { get; set; }
        public string Creator { get; set; }
        public string CreatorID { get; set; }
        public string IsCompleted { get; set; }
        public string IsUsed { get; set; }
        public string Team { get; set; }
        public string Program { get; set; }
        public string ProjectType { get; set; }
        public string County { get; set; }
        public string Engagement { get; set; }
        public string Responsibility { get; set; }
        public string LeadPersonID { get; set; }
        public string Objectives { get; set; }
        public string Outputs { get; set; }
        public string Outcomes { get; set; }
        public string When { get; set; }
        public string Where { get; set; }
        public string Evaluation { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Modified_By { get; set; }
        public string Instructors { get; set; }
    }
}
