//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POW_REST_2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectLeadPerson
    {
        public int ID { get; set; }
        public int ProjectID { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<bool> IsUsed { get; set; }
    }
}
