//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POW_REST_2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffDirectory
    {
        public string UserID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string PreferredFirstName { get; set; }
        public string EmailAddress { get; set; }
        public string Division { get; set; }
        public string JobTitle { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string IsUsed { get; set; }
        public string PlanningUnit { get; set; }
        public string PositionNumber { get; set; }
        public string SupervisorNumber { get; set; }
        public Nullable<System.DateTime> HiredDate { get; set; }
        public Nullable<System.DateTime> PromotedDate { get; set; }
        public string MajorProgram { get; set; }
        public string StaffPicture { get; set; }
        public string Affiliate { get; set; }
        public string Department2 { get; set; }
        public string street { get; set; }
        public string street2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string Phone { get; set; }
        public string mobile { get; set; }
        public string TimekeepingLocation { get; set; }
    }
}
