//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POW_REST_2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDeskAuditsNEW
    {
        public int ID { get; set; }
        public Nullable<int> SPID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string FileRef { get; set; }
        public string County { get; set; }
        public string field365 { get; set; }
        public string field366 { get; set; }
        public string field367 { get; set; }
        public string field368 { get; set; }
        public string field369 { get; set; }
        public string field370 { get; set; }
        public string field371 { get; set; }
        public string field372 { get; set; }
        public string field373 { get; set; }
        public string field374 { get; set; }
        public string field375 { get; set; }
        public string field496 { get; set; }
        public string field497 { get; set; }
        public string field498 { get; set; }
        public Nullable<bool> IsUsed { get; set; }
        public Nullable<bool> IsSubmitted { get; set; }
    }
}
