//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POW_REST_2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDeskAudit
    {
        public int ID { get; set; }
        public Nullable<int> SPID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string FileRef { get; set; }
        public string County { get; set; }
        public string Efforts { get; set; }
        public string Success { get; set; }
        public string IsUsed { get; set; }
        public string REA { get; set; }
        public Nullable<bool> IsSubmitted { get; set; }
        public string Year { get; set; }
    }
}
