//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POW_REST_2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOtherAdviser
    {
        public int ID { get; set; }
        public Nullable<int> PID { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string otherAdvisoryGroup { get; set; }
        public string otherWhite { get; set; }
        public string otherBlack { get; set; }
        public string otherAsianPacific { get; set; }
        public string otherIndian { get; set; }
        public string otherOther { get; set; }
        public string otherNotDetermined { get; set; }
        public string otherHispanic { get; set; }
        public string otherFemales { get; set; }
        public string otherMales { get; set; }
        public string otherMeetings { get; set; }
        public string otherAttendance { get; set; }
        public Nullable<System.DateTime> otherBylaws { get; set; }
        public string otherCouncil { get; set; }
    
        public virtual tblCivilRight tblCivilRight { get; set; }
    }
}
