//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POW_REST_2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCountySet
    {
        public int ID { get; set; }
        public Nullable<int> CountyID { get; set; }
        public string CountyName { get; set; }
        public Nullable<bool> IsUrban { get; set; }
        public string Set { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string SetName { get; set; }
    }
}
