//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string ProjectID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Year { get; set; }
        public string IsUsed { get; set; }
        public string Event { get; set; }
        public string Recurrence { get; set; }
        public string UpdateMode { get; set; }
        public string Creator { get; set; }
        public string CreatorID { get; set; }
        public string Participants { get; set; }
        public string Team { get; set; }
        public string Program { get; set; }
        public string StartTime { get; set; }
        public string Duration { get; set; }
        public string IsPublic { get; set; }
        public string County { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Appointment { get; set; }
        public string Address { get; set; }
        public string Fee { get; set; }
        public string Phone { get; set; }
        public string URL { get; set; }
        public string description { get; set; }
        public string ContactName { get; set; }
        public string ContactEmail { get; set; }
        public string AnnounceCounty { get; set; }
    }
}
