//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactApp
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> ActivityID { get; set; }
        public Nullable<int> Attendees { get; set; }
        public string ContactType { get; set; }
        public string Program { get; set; }
        public string Year { get; set; }
        public string Description { get; set; }
        public string raian { get; set; }
        public string rapi { get; set; }
        public string rblack { get; set; }
        public string rfmale { get; set; }
        public string rhisp { get; set; }
        public string rmale { get; set; }
        public string rnftf { get; set; }
        public string rother { get; set; }
        public string rwhite { get; set; }
        public string ryouth { get; set; }
        public string uadult { get; set; }
        public string uaian { get; set; }
        public string uapi { get; set; }
        public string ublack { get; set; }
        public string ufmale { get; set; }
        public string uhisp { get; set; }
        public string umale { get; set; }
        public string unftf { get; set; }
        public string uother { get; set; }
        public string uwhite { get; set; }
        public string uyouth { get; set; }
        public string CreatorID { get; set; }
        public string IsUsed { get; set; }
        public string radult { get; set; }
        public string Evaluation { get; set; }
        public string ExternalFactor { get; set; }
        public string Outcomes { get; set; }
        public string FileLink { get; set; }
        public string County { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string rMore { get; set; }
        public string uMore { get; set; }
        public string IsPlan { get; set; }
    }
}
